namespace Session_10_OOP_Demo.Partial
{
    // ka2n el 3amlt el file dah el hwa el Class bta3 el Employee dah el 3amloh 
    // hwa el Entity Framework Core
    // we hatla2t el Enty Framework Core lma y generate 7aga zay el Class dah hyktb ==> Auto Generated by Core
    // we bydef 3aleh el Keyword ==> [Partial]
    // we tab3n me4 han3dl hean wla han3ml ay 7aga feh l2n mogard ay ta3del hwa byms7 el 2dem
    // we y3ml create ll gded we dah 27na me4 3ayzenoh 3l4an kdah 
    // ro7t 3aml Class tany be nafs el 2sm el hwa Employee
    // han3ml feh kol el ta3delat el 27na 3ayzenha bera7tena mn 8er ma negy gamb el Class el hean dah 
    // we anta tab3n lam te3ml el Class el tany bta3 el Employee bardo hatro7 t7ot 
    // el Keyword ==> [Partial] 3l4an el Entity FrameWork Core yfham 2n el 2 Files dol 2w el 2 Classes dol
    // ma3 ba3d we fe mar7let el Compile hygam3 el 2 partial Classes fe 1 Class 2smoh Employee

    // el Partial Class 3ady y inherit mn ay Class 3ady 
    // law 7awlt t5aly el file dah y inherit mn class 
    // we el file el tany y inherit mn class tany 
    // dah kdah hydrb error l2nk kedh bet7awl te3ml multiple inheritance we dah 8er masmo7 beh
    // lakn law 3amlt hena inherit mn class msln parent
    // we henak 3amlt inherit mn nafs class el parent
    // 3ady ma hwa 4ayfhom nafs el class me4 2enk bet3ml multiple inheritance l2a 

    // 3ady gwah el partial class te3ml override law fe 7aga virtual  mn el class el bet inherit menoh
    // we 3ady te3ml 3aleha [sealed] 3l4an ma7d4 ywresha ba3dk 
    // ya3ny mn el 25er ka2nk bett3aml ma3 el partial class ka2noh hwa class 3ady ela fe 7awr el method
    // el 4ar7nah ta7t 

    // we 3ady ay 7ad ywres mn el partial class 
    // te2dr te3ml 2kre mn partial class fe 2ktr mn file we t2smhom bra7tk

    // law 3amlt Class 2esmoh Employee fe folder tany 7er folder el partial dah malo4 3elak bel 
    // class el employee el hena 
    // 3l4an ykon lehom 3elaka be ba3d lazem nafs el folder we nafs el namesapce

    // 3ady tet3aml ma3 static members gwa el partial class bta3k 3ady 
    internal partial class Employee
    {
        // hena 3andy 3 properties 
        // we henak 3and 1 method
        // el 3ayez 23mloh hwa 2ny 2bd2 2t3aml ma3 el Employee ka kol 
        // el hwa yb2a 4ayef el method we el 3 properties
        // 5las yala han3ml dah fe el Progeam.cs
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Age { get; set; }

        // ha3ml method DoSomeThing betetba3 7aga we hatro7 te nady 3al method el Print
        // el fe el partial Class el tany
        // we dah 3ady ma el 2 Partial Classes of Emplyoees 4ayfen ba3d 3ady 
        // bs law el developer el tany el by3ml el file el tany el by3ml el partial class el tany
        // ra7 3aml Comment ll method el 2smha Print() henak eh el hy7sl hena ????
        // kdah hena hydrb error l2noh mab24 4ayef 7aga fe el file el tany wsmha Print()
        // l2 2t3mlha Comment 5las 
        // fa 27na me7tagen ne3ml 2etefa2 mabena
        // el 2tefe2a el mabena ha2loh feh ana me7taga menk y developer y tany yaly 4a8l 3al el file el tany
        // ykon 3andk method 2smaha Print() 3l4an ana hast5dmha 
        // ya3ny me7taga a22olh lazem yb2a 3andk ==> public void Print();
        // bs law 3amltha 3al kdh bs hwa kdah el compiler za3lan we darb error
        // l2n deh kdah to3tabr signature method we 27ena mynfa34 no7t signature method fe class 3ady
        // el signature method bett7at fe el interface
        // fa 7al el error dah el compiler by2olk
        // y tro7 test5dm el  ==> [abstract]  bs ana hena me4 fe abstract class fa dah me4 hynf3
        // 2w tro7 test5dm el ==> [extern] dah mawdo3 kber me4 hynfa3 
        // 2w tro7 test5dm el ==> [partial] that mean this method will be partial implementation
        // we hya deh 2nsb 7al 
        // we kdah ana henak fe el file el tany el partial mestany menk tekml el implemention
        // bta3ha ya3ny te3ml el behvior bta3ha 2w el body bta3ha fe el file el tany
        // fa hateb2a hena kdah ==> public partial void Print();
        // bs ta3la kdah ne3ml 7araka han4el public menha we teb2a kdah ==>  partial void Print();
        // hal2eh me4 za3lan we ba2 tmam 
        // l2n el method ba2t [Void] ka2ny ba2olh 2enta kman 4waya me7tag t3eml el Print()
        // [Void]==> Ma3na Void 2enha ba2t [Optional Implementation] ya3ny 3amlta 2w ma 3amltha4 me4 hatefr2
        // fa law 3amltha el Compiler hy3ml Compile we 7a3ml el behvior bta3ha ya3ny h3ady 3aleha
        // lakn law ma 3amltha4 el Compiler hytgahlha k2nk me4 3amltha
        // ka2nk me4 katb el satr dah  ==> partial void Print();
        // hya lazem tkon Void l2n 
        // lakn law rag3t el [public] tany kdah mab2a4 optional implementation we kdah mogbr 
        // 2ny 23ml el implementation bta3ha henak fe el file el tany
        // tb law 3amlt kdah ==> partial int PrintNum();
        // deh kdah ==> [Non-Void]
        // [Non-Void] ==> Ma3naha 2naha Mandatory Implementation ya3ny lazem 23mlh el implemention 8asb 3any heank
        // we kman hyb2a darb error tany l2n me4 3amlha el access modifier bta3h ya3ny me4 m7add hya public wla private wla eh 
        // el mohm han3m el Print deh ==> partial void Print();
        // we ha n run hanl2eh by run 3ady 7ata we ana 3amlha Comment fe el file el tany 
        // l2nha hena void ya3ny optioanl implementation 3amltha tmama ma 3amltha4 tamam bardo
        // tb law 4elt el Comment men hena hydrb error fe el file el tany tb leh ??
        // l2nha henak public we hya hena private we el mafrod henak yb2a zay hena fa 5las ha4el el 
        // public men henak we teb2a private
        // bs hal2y lesa feh mo4kela l2enha hena hya partial we henak hya me4 partial fa lazem 25leha
        // hya kman teb2a partual henak bardo 
        // lazem el 2 method hena we henak lehom nafs el access modifier zay ba3d bel zabt 
        // bs ana kont ba call el method el print deh fe el Program lama kant public
        // we delw2ty b2t hya private fa hydrb error tab3n 
        // fa 5las har97 23mlha hena we heank 2enha public me4 private 3l4an kolo y4ta8l kways
    

        //public void Print();

         public partial void Print(); //[public] tany kdah mab2a4 optional implementation we kdah mogbr 
                                     // 2ny 23ml el implementation bta3ha henak fe el file el tany

       //partial void Print(); // Void ==> Optional Implementation

        partial void Hello(int x); // Void ==> Optional Implementation 7at law beta5od parameter bardo

        public partial int PrintNum(); // Non-Void ==> Mandatory Implementation 
        public void DoSomeThing()
        {
            Console.WriteLine($"Hello From Do SomeThing");
            Print();
            Console.WriteLine(PrintNum());
            Hello(20);
        }

        // han3mlha access bel Class name me4 mn el instance l2n dah static method 
        public static void SayHello()
        {
            Console.WriteLine("Hello i am tired :(");
        }
    }
}
